# Server
server.port=8080

# H2 Database
spring.datasource.url=jdbc:h2:mem:secretdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# NATS Configuration
nats.url=nats://localhost:4222
nats.tls.enabled=false


# Crypto Configuration
crypto.password.length=32

# Message Configuration
message.max.tries=3
message.expiry.days=2

# Security
spring.security.user.name=admin
spring.security.user.password=admin
